### ISSUE TITLE
Is this only for coaches?

### ISSUE THREAD

**Issue by corysimmons** [jb-1980/khan-graphql#4]
I'd like to write a frontend to track my progress for myself, but I'm not a coach/teacher.

**Comment by jb-1980** [comment]
I have not looked into all the details, but I am sure that Khan Academy is calling the graphql endpoint to get your data. So you will just have to monitor and implement the graphql calls as detailed in https://github.com/jb-1980/khan-graphql/blob/master/CONTRIBUTING.md.

Note that you can create the frontend to display the data, but you will have to create a backend node service to pull the data. This script won't work in the browser.

Here is a codesandbox to give you an idea: https://codesandbox.io/s/basic-khan-graphql-server-cjvp6?file=/src/index.js

**Comment by corysimmons** [comment]
Yup, I can whip up a Node server. Was just checking if the endpoints/resolvers/etc would be restricted to `Authorization: Bearer SOME_TOKEN_GENERATED_FOR_COACHES_ONLY`.

Thank you!
